import { type NextPage } from "next";
import Head from "next/head";
import {
    type MovieContextType,
    useMovies,
    type Movie,
} from ".././MoviesContext";
import { type Dispatch, type SetStateAction, useState, useRef } from "react";
import { useOutsideClickDetector } from "~/utils/outsideClick";

interface MoviesListProps {
    moviesList: Movie[];
}

const MoviesList: ({ moviesList }: MoviesListProps) => JSX.Element = ({
    moviesList,
}: MoviesListProps) => {
    return (
        <ul className="max-w-md list-inside list-disc space-y-2 text-lg text-neutral-200 md:text-xl">
            {moviesList.map((movie: Movie) => (
                <li key={movie.name}>{movie.name}</li>
            ))}
        </ul>
    );
};

const AddMoviePortal = ({
    setState,
}: {
    setState: Dispatch<SetStateAction<boolean>>;
}) => {
    const [movieName, setMovieName] = useState<string>("");
    const { addMovieToList } = useMovies();
    const addMoviePortalRef = useRef<HTMLDivElement>(null);

    useOutsideClickDetector(addMoviePortalRef, () => setState(false));

    return (
        <div
            ref={addMoviePortalRef}
            className="absolute left-1/2 top-1/2 z-20 -ml-[8.75rem] -mt-[8.75rem] h-[17.5rem] w-[17.5rem] rounded-sm border border-neutral-700 bg-neutral-900 shadow-xl md:-ml-[15rem] md:-mt-[12.5rem] md:h-[30rem] md:w-[35rem]"
        >
            <div className="flex w-full justify-end p-3 md:p-5">
                <button onClick={() => setState(false)}>
                    <svg
                        className="h-5 w-5 fill-neutral-400 md:h-8 md:w-8"
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 384 512"
                    >
                        <path d="M376.6 84.5c11.3-13.6 9.5-33.8-4.1-45.1s-33.8-9.5-45.1 4.1L192 206 56.6 43.5C45.3 29.9 25.1 28.1 11.5 39.4S-3.9 70.9 7.4 84.5L150.3 256 7.4 427.5c-11.3 13.6-9.5 33.8 4.1 45.1s33.8 9.5 45.1-4.1L192 306 327.4 468.5c11.3 13.6 31.5 15.4 45.1 4.1s15.4-31.5 4.1-45.1L233.7 256 376.6 84.5z" />
                    </svg>
                </button>
            </div>
            <div className="flex w-full flex-col items-center justify-center gap-6 p-3 text-center md:p-8">
                <label
                    htmlFor="movieName"
                    className="text-base font-normal text-neutral-300 md:my-4 md:text-lg"
                >
                    Enter Name of the movie you want to add
                </label>
                <input
                    type="text"
                    id="movieName"
                    name="movieName"
                    placeholder="Movie Name"
                    className="block w-full rounded-sm border border-gray-600 bg-gray-700 p-2 text-sm text-gray-400 placeholder-gray-400 focus:border-blue-500 focus:ring-blue-500 md:mb-6 md:p-2.5"
                    value={movieName}
                    onChange={(e) => setMovieName(e.target.value)}
                    autoFocus={true}
                />
                <button
                    onClick={() => {
                        addMovieToList({ name: movieName });
                        setState(false);
                    }}
                    className="w-full rounded-sm bg-green-700 py-2 text-base text-neutral-300 transition-all hover:bg-green-800 hover:text-neutral-200 md:py-3 md:text-lg"
                >
                    Continue
                </button>
            </div>
        </div>
    );
};

const Home: NextPage = () => {
    const { moviesList }: MovieContextType = useMovies();

    const [addMoviePortalOpen, setAddMoviePortalOpen] =
        useState<boolean>(false);

    return (
        <>
            <Head>
                <title>Olsa&apos;s movie recommendations</title>
                <meta name="description" content="Generated by create-t3-app" />
                <meta
                    name="viewport"
                    content="width=device-width, minimum-scale=1.0, maximum-scale = 1.0, user-scalable = no"
                ></meta>
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div id="stars"></div>
            {/* <div id="stars2"></div> */}
            {/* <div id="stars3"></div> */}

            {addMoviePortalOpen && (
                <AddMoviePortal setState={setAddMoviePortalOpen} />
            )}

            <main className="flex min-h-screen flex-col items-center justify-start overflow-x-hidden px-3 md:px-6">
                <section className="flex h-full flex-col items-start justify-center gap-10 py-10 md:gap-14 md:py-14">
                    <h1 className="text-center text-xl font-black text-gray-200 md:text-3xl">
                        Welcome to Olsa&apos;s 🪐 movie recommendation list!
                    </h1>
                    <div className="flex h-full w-full flex-col items-center justify-center">
                        <div className="mb-8 flex w-full flex-col items-center justify-between gap-6 md:mb-10 md:flex-row">
                            <button
                                onClick={() => alert("🌷")}
                                className="flex items-center justify-center"
                            >
                                <span className="cursor-pointer text-base font-medium text-neutral-400 transition-all hover:text-neutral-200 md:text-lg">
                                    Nothing to see here <br></br>don&apos;t
                                    click this c:
                                </span>
                            </button>
                            <div className="hidden items-center justify-center md:flex">
                                <h2 className="text-lg font-bold text-neutral-300 md:text-xl">
                                    Total Movies: {moviesList.length}
                                </h2>
                            </div>
                            <button
                                onClick={() =>
                                    setAddMoviePortalOpen(
                                        (prevAddMoviePortalOpen: boolean) =>
                                            !prevAddMoviePortalOpen
                                    )
                                }
                                className="flex items-center justify-center"
                            >
                                <span className="flex cursor-pointer items-center justify-center gap-3 fill-neutral-400 text-base font-medium text-neutral-400 transition-all hover:fill-neutral-200 hover:text-neutral-200 md:gap-5 md:text-lg">
                                    Add movie to list{" "}
                                    <span>
                                        <svg
                                            className="h-4 w-4 md:h-5 md:w-5"
                                            xmlns="http://www.w3.org/2000/svg"
                                            viewBox="0 0 448 512"
                                        >
                                            <path d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32V224H48c-17.7 0-32 14.3-32 32s14.3 32 32 32H192V432c0 17.7 14.3 32 32 32s32-14.3 32-32V288H400c17.7 0 32-14.3 32-32s-14.3-32-32-32H256V80z" />
                                        </svg>
                                    </span>
                                </span>
                            </button>
                            <div className="flex items-center justify-center md:hidden">
                                <h2 className="text-lg font-bold text-neutral-300 md:text-xl">
                                    Total Movies: {moviesList.length}
                                </h2>
                            </div>
                        </div>
                    </div>
                </section>
                <section className="flex h-full w-full items-center justify-center pb-[50rem] md:pb-96">
                    <MoviesList moviesList={moviesList} />
                </section>
            </main>
        </>
    );
};

export default Home;
