import { NextComponentType, type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

interface Movie {
    id: number;
    name: string;
}

interface MovieListProps {
    movieList: Movie[];
}

const MovieList: any = ({ movieList }: MovieListProps) => {
    return (
        <ul className="max-w-md list-inside list-disc space-y-1 text-neutral-200">
            {movieList.map((movie: Movie) => (
                <li key={movie.id}>{movie.name}</li>
            ))}
        </ul>
    );
};

const Home: NextPage = () => {
    const [movieList, setMovieList] = useState([
        {
            name: "Inglorious Basterds",
            id: 1,
        },
        {
            name: "War Dogs",
            id: 2,
        },
        {
            name: "Interstellar",
            id: 3,
        },
    ]);

    return (
        <>
            <Head>
                <title>Olsa&apos;s movie reccomendation list</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <section className="flex h-[60vh] flex-col items-start justify-center">
                    <h1 className="text-center text-4xl font-black text-white">
                        Welcome to Olsa&apos;s movie reccomendation list!
                    </h1>
                    <div className="flex h-full w-full flex-col items-center justify-center">
                        <div className="flex w-full justify-between">
                            <div>
                                <span className="cursor-pointer text-xl font-medium text-neutral-400 transition-all hover:text-neutral-200">
                                    Link to somewhere
                                </span>
                            </div>

                            <div className="mb-12 flex justify-center">
                                <h2 className="text-2xl font-bold text-neutral-300">
                                    Movies:
                                </h2>
                            </div>
                            <div>
                                <span className="cursor-pointer text-xl font-medium text-neutral-400 transition-all hover:text-neutral-200">
                                    Add movie to list +
                                </span>
                            </div>
                        </div>
                        <MovieList movieList={movieList} />
                    </div>
                </section>
            </main>
        </>
    );
};

export default Home;
